# Generated by Django 5.1.2 on 2024-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.TextField(max_length=300)),
                ('encargado', models.TextField(max_length=300)),
                ('servicio', models.TextField(max_length=300)),
                ('ganancias', models.FloatField(max_length=100)),
            ],
        ),
    ]
