# Generated by Django 5.1.2 on 2024-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField(max_length=300)),
                ('estado', models.CharField(max_length=100)),
                ('caducidad', models.DateField(max_length=100)),
            ],
        ),
    ]
