# Generated by Django 5.1.2 on 2024-11-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('codigoper', models.CharField(max_length=6)),
                ('codigopro', models.CharField(max_length=6)),
                ('codigocli', models.CharField(max_length=6)),
                ('fecha', models.DateField(max_length=100)),
                ('cantidad', models.CharField(max_length=6)),
                ('total', models.FloatField(max_length=100)),
            ],
        ),
    ]
