# Generated by Django 5.1.2 on 2024-11-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(max_length=300)),
                ('telefono', models.TextField(max_length=300)),
                ('giro', models.TextField(max_length=300)),
            ],
        ),
    ]
